/* Generated by AN DISI Unibo */ 
package it.unibo.sender

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sender ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("---------- sender forward m2")
						forward("m2", "m2(1)" ,"worker" ) 
						delay(100) 
						println("---------- sender forward m1")
						forward("m1", "m1(1)" ,"worker" ) 
						delay(100) 
						println("---------- sender forward m1")
						forward("m2", "m2(2)" ,"worker" ) 
						delay(100) 
						println("---------- sender forward m2")
						forward("m2", "m2(3)" ,"worker" ) 
						delay(500) 
						println("---------- sender forward m1")
						forward("m1", "m1(2)" ,"worker" ) 
						delay(4000) 
						println("---------- sender forward m1")
						forward("m1", "m1(3)" ,"worker" ) 
						delay(1000) 
						println("---------- sender forward m1")
						forward("m1", "m1(4)" ,"worker" ) 
						delay(1000) 
						println("---------- sender forward m2")
						forward("m2", "m2(4)" ,"worker" ) 
					}
				}	 
			}
		}
}
