/* Generated by AN DISI Unibo */ 
package it.unibo.nanorobot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Nanorobot ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("nanorobot | START")
						robotNano.nanoSupport.create(myself)
						robotNano.nanoSupport.move( "z"  )
						delay(1000) 
						robotNano.nanoSupport.move( "x"  )
						updateResourceRep( "stopped"  
						)
						  //For real robots
						 			var realsonar = context!!.hasActor("realsonar")  
						 			if( realsonar != null ){ 
						 				println("nanorobot | WORKING IN A REAL ENV") 
						 				//ACTIVATE THE DATA SOURCE realsonar
						 				forward("sonarstart", "sonarstart(1)" ,"realsonar" ) 				
						 				//SET THE PIPE
						 				realsonar.
						 				subscribeLocalActor("datacleaner").
						 				subscribeLocalActor("distancefilter").
						 				subscribeLocalActor("nanorobot")		//in order to perceive obstacle
						 			}else{
						 				println("nanorobot | WARNING: realsonar NOT FOUND")
						 			}
						discardMessages = false
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
					}
					 transition(edgeName="t10",targetState="execcmd",cond=whenDispatch("cmd"))
					transition(edgeName="t11",targetState="handleObstacle",cond=whenEvent("obstacle"))
				}	 
				state("execcmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("cmd(X)"), Term.createTerm("cmd(MOVE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "move(${payloadArg(0)})"  
								)
								robotNano.nanoSupport.move( payloadArg(0)  )
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handleObstacle") { //this:State
					action { //it:State
						println("basicrobot | handleObstacle")
						robotNano.nanoSupport.move( "h"  )
						if( checkMsgContent( Term.createTerm("obstacle(ARG)"), Term.createTerm("obstacle(TARGET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep( "obstacle"  
								)
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
