/* Generated by AN DISI Unibo */ 
package it.unibo.roomboudaryexplorer

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Roomboudaryexplorer ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
		val mapname     = "roomBoundary"  		 
		var NumStep     = 0
		 
		//REAL ROBOT
		//var StepTime   = 1000	 
		 
		//VIRTUAL ROBOT
		 var StepTime   = 350	 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						itunibo.planner.plannerUtil.initAI(  )
						delay(500) 
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						delay(300) 
						forward("cmd", "cmd(r)" ,"basicrobot" ) 
						delay(300) 
					}
					 transition(edgeName="t00",targetState="work",cond=whenDispatch("cmd"))
				}	 
				state("work") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="detectBoundary", cond=doswitch() )
				}	 
				state("detectBoundary") { //this:State
					action { //it:State
						 NumStep++  
						itunibo.planner.plannerUtil.showCurrentRobotState(  )
						updateResourceRep( "detectBoundary $NumStep"  
						)
					}
					 transition( edgeName="goto",targetState="doAheadMove", cond=doswitchGuarded({ (NumStep<5)  
					}) )
					transition( edgeName="goto",targetState="boundaryFound", cond=doswitchGuarded({! ( (NumStep<5)  
					) }) )
				}	 
				state("doAheadMove") { //this:State
					action { //it:State
						request("step", "step($StepTime)" ,"basicrobot" )  
						updateResourceRep( "doAheadMove"  
						)
					}
					 transition(edgeName="t01",targetState="stepDone",cond=whenReply("stepdone"))
					transition(edgeName="t02",targetState="stepFailed",cond=whenReply("stepfail"))
				}	 
				state("stepDone") { //this:State
					action { //it:State
						updateResourceRep( itunibo.planner.moveUtils.getMapOneLine()  
						)
						itunibo.planner.plannerUtil.updateMap( "w"  )
					}
					 transition( edgeName="goto",targetState="doAheadMove", cond=doswitch() )
				}	 
				state("stepFailed") { //this:State
					action { //it:State
						println("robotmapper | FOUND A WALL")
						if( checkMsgContent( Term.createTerm("stepfail(DURATION,CAUSE)"), Term.createTerm("stepfail(DURATION,CAUSE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var Dt = payloadArg(0).toLong() / 4   
								println("robotmapper | stepFail after: $Dt vs ${3*StepTime/4.0}")
								if(  Dt < 3*StepTime/4.0   
								 ){forward("cmd", "cmd(s)" ,"basicrobot" ) 
								delay(Dt)
								forward("cmd", "cmd(h)" ,"basicrobot" ) 
								}
								if(  ! itunibo.planner.plannerUtil.atHome()  
								 ){itunibo.planner.plannerUtil.wallFound(  )
								}
						}
						updateResourceRep( "found a wall"  
						)
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						delay(500) 
						itunibo.planner.plannerUtil.updateMap( "l"  )
						itunibo.planner.plannerUtil.showCurrentRobotState(  )
					}
					 transition( edgeName="goto",targetState="detectBoundary", cond=doswitch() )
				}	 
				state("boundaryFound") { //this:State
					action { //it:State
						itunibo.planner.moveUtils.saveRoomMap( mapname  )
						println("robotmapper | FINAL MAP")
						itunibo.planner.plannerUtil.showCurrentRobotState(  )
						updateResourceRep( itunibo.planner.moveUtils.getMapOneLine()  
						)
						 println(itunibo.planner.moveUtils.getMapOneLine())  
						terminate(0)
					}
				}	 
			}
		}
}
