/* Generated by AN DISI Unibo */ 
package it.unibo.qa0

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Qa0 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("Hello world")
						forward("msg1", "msg1(hello1)" ,"qa0" ) 
						forward("msg1", "msg1(hello2)" ,"qa0" ) 
					}
					 transition(edgeName="t00",targetState="work",cond=whenDispatch("msg1"))
				}	 
				state("work") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("qa0 in state work")
						stateTimer = TimerActor("timer_work", 
							scope, context!!, "local_tout_qa0_work", 500.toLong() )
					}
					 transition(edgeName="t01",targetState="end",cond=whenTimeout("local_tout_qa0_work"))   
					transition(edgeName="t02",targetState="work",cond=whenDispatch("msg1"))
				}	 
				state("end") { //this:State
					action { //it:State
						println("qa0 ENDS")
					}
				}	 
			}
		}
}
