/* Generated by AN DISI Unibo */ 
package it.unibo.ctxgettaskstudent2
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "dontcare1", this, "gettaskstudent2.pl", "sysRules.pl"
	)
}

