/* Generated by AN DISI Unibo */ 
package it.unibo.callerco1

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Callerco1 ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("caller1 request cmd ")
						request("cmd", "cmd(callerco1)" ,"resourceandco" )  
					}
					 transition(edgeName="t04",targetState="handleReply",cond=whenReply("replytocmd"))
					transition(edgeName="t05",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleReply") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						delay(5000) 
						println("       --- caller1 handleReply: emit fire")
						emit("alarm", "alarm(fire)" ) 
					}
					 transition(edgeName="t06",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
				state("handleAlarm") { //this:State
					action { //it:State
						println("       --- caller1 handleAlarm   ")
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t07",targetState="handleReply",cond=whenReply("replytocmd"))
					transition(edgeName="t08",targetState="handleAlarm",cond=whenEvent("alarm"))
				}	 
			}
		}
}
