/* Generated by AN DISI Unibo */ 
package it.unibo.basicrobot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Basicrobot ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
		  var StepTime      = 0L
		  var StartTime     = 0L    
		  var Duration      = 0L    
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("basicrobot | START")
						unibo.robot.robotSupport.create(myself ,"basicrobotConfig.json" )
						unibo.robot.robotSupport.move( "l"  )
						unibo.robot.robotSupport.move( "r"  )
						updateResourceRep("stopped")
						discardMessages = false
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
					}
					 transition(edgeName="t10",targetState="handleCollision",cond=whenDispatch("collision"))
					transition(edgeName="t11",targetState="execcmd",cond=whenDispatch("cmd"))
					transition(edgeName="t12",targetState="doStep",cond=whenRequest("step"))
					transition(edgeName="t13",targetState="endwork",cond=whenDispatch("end"))
				}	 
				state("handleCollision") { //this:State
					action { //it:State
						println("basicrobot | handleCollision")
						if( checkMsgContent( Term.createTerm("collision(TARGET)"), Term.createTerm("collision(TARGET)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep("collision")
								emit("collision", "collision(obstacle)" ) 
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("execcmd") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("cmd(MOVE)"), Term.createTerm("cmd(MOVE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								updateResourceRep("move(${payloadArg(0)})")
								unibo.robot.robotSupport.move( payloadArg(0)  )
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("doStep") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("step(TIME)"), Term.createTerm("step(T)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
									StepTime = payloadArg(0).toLong() 	 
								updateResourceRep("step(${StepTime})")
								println("basicrobot | doStep StepTime =$StepTime ")
								unibo.robot.robotSupport.move( "w"  )
								StartTime = getCurrentTime()
						}
						stateTimer = TimerActor("timer_doStep", 
							scope, context!!, "local_tout_basicrobot_doStep", StepTime )
					}
					 transition(edgeName="t04",targetState="stepPerhapsDone",cond=whenTimeout("local_tout_basicrobot_doStep"))   
					transition(edgeName="t05",targetState="stepFail",cond=whenDispatch("collision"))
				}	 
				state("stepPerhapsDone") { //this:State
					action { //it:State
						unibo.robot.robotSupport.move( "h"  )
						stateTimer = TimerActor("timer_stepPerhapsDone", 
							scope, context!!, "local_tout_basicrobot_stepPerhapsDone", StepTime )
					}
					 transition(edgeName="t06",targetState="stepDone",cond=whenTimeout("local_tout_basicrobot_stepPerhapsDone"))   
					transition(edgeName="t07",targetState="stepFailDetected",cond=whenDispatch("collision"))
				}	 
				state("stepDone") { //this:State
					action { //it:State
						unibo.robot.robotSupport.move( "h"  )
						println("basicrobot | stepDone ")
						updateResourceRep("stepDone")
						answer("step", "stepdone", "stepdone(ok)"   )  
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("stepFailDetected") { //this:State
					action { //it:State
						println("basicrobot | stepFailDetected near end of step ")
						answer("step", "stepfail", "stepfail($StepTime,obstacle)"   )  
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("stepFail") { //this:State
					action { //it:State
						Duration = getDuration(StartTime)
						updateResourceRep("stepFail($Duration)")
						println("basicrobot | stepFail after $Duration ")
						emit("collision", "collision(obstacle)" ) 
						answer("step", "stepfail", "stepfail($Duration,obstacle)"   )  
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("endwork") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("end(ARG)"), Term.createTerm("end(V)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								println("basicrobot | endwork")
								updateResourceRep("move(end)")
								utils.virtualRobotSupportQak.terminatevr(  )
						}
						emit("endall", "endall(normal)" ) 
						terminate(1)
					}
				}	 
			}
		}
}
