/* Generated by AN DISI Unibo */ 
package it.unibo.ctxres1
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "caller1.pl", "sysRules.pl"
	)
}

