/* Generated by AN DISI Unibo */ 
package it.unibo.ctxcallerb
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "demo_req_b.pl", "sysRules.pl"
	)
}

