/* Generated by AN DISI Unibo */ 
package it.unibo.ctxfortrustingwalker
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "dontcare", this, "skilledwalker.pl", "sysRules.pl"
	)
}

