/* Generated by AN DISI Unibo */ 
package it.unibo.ctxgettaskstudent1
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "somehost1", this, "gettaskstudent1.pl", "sysRules.pl"
	)
}

