/* Generated by AN DISI Unibo */ 
package it.unibo.ctxgettaskdeploy
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "dontcare2", this, "gettaskstudent2.pl", "sysRules.pl"
	)
}

