/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sonar ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 val simulate = false
		   lateinit var firstActorInPipe : ActorBasic 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						discardMessages = true
						println("sonar started")
						  if( simulate ) firstActorInPipe = sysUtil.getActor("sonarsimulator")!!  //generates simulated data
									else firstActorInPipe = sysUtil.getActor("sonardatasource")!! 			//generates REAL data
						 			firstActorInPipe.
									subscribeLocalActor("datacleaner"). 		//removes 'wrong' data''
									subscribeLocalActor("datalogger").		    //logs (shows) the data generated by the sonar
						  			//subscribeLocalActor("sonar").				//handles sonarRobot but does not propagate ...
						 			subscribeLocalActor("distancefilter").		//propagates the lcoal stream event obstacle
						  			subscribeLocalActor("sonar")  
						if(  simulate  
						 ){forward("simulatorstart", "simulatorstart(qasource)" ,"sonarsimulator" ) 
						}
						else
						 {forward("simulatorstart", "simulatorstart(qasource)" ,"sonardatasource" ) 
						 }
					}
					 transition(edgeName="t00",targetState="handleObstacle",cond=whenEvent("obstacle"))
				}	 
				state("handleObstacle") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t01",targetState="handleObstacle",cond=whenEvent("obstacle"))
					transition(edgeName="t02",targetState="handleEvent",cond=whenEvent("sonarRobot"))
				}	 
				state("handleEvent") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
					}
					 transition(edgeName="t03",targetState="handleEvent",cond=whenEvent("sonarRobot"))
					transition(edgeName="t04",targetState="handleEvent",cond=whenEvent("obstacle"))
				}	 
			}
		}
}
