/* Generated by AN DISI Unibo */ 
package it.unibo.sonar

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Sonar ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("sonar started")
						sensors.sonarHCSR04Support.create(myself)
					}
					 transition(edgeName="t00",targetState="handleEvent",cond=whenEvent("sonarRobot"))
				}	 
				state("handleEvent") { //this:State
					action { //it:State
					}
					 transition(edgeName="t01",targetState="handleEvent",cond=whenEvent("sonarRobot"))
				}	 
			}
		}
}
