/* Generated by AN DISI Unibo */ 
package it.unibo.robotboundary

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Robotboundary ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
		var NumStep      = 0
		val StepTime     = 350
		var StartTime    = 0L
		var Workduration = 0L 
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("robotboundary | START")
						discardMessages = false
						println("${mapRoomKotlin.mapUtil.refMapForTesting}")
						println("-----------------")
						mapRoomKotlin.mapUtil.showMap(  )
						delay(2000) 
						updateResourceRep("initial")
					}
					 transition(edgeName="t00",targetState="startWork",cond=whenDispatch("start"))
				}	 
				state("startWork") { //this:State
					action { //it:State
						StartTime = getCurrentTime()
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("robotboundary | working ${NumStep}")
						request("step", "step($StepTime)" ,"basicrobot" )  
						updateResourceRep("working")
					}
					 transition(edgeName="t01",targetState="stepDone",cond=whenReply("stepdone"))
					transition(edgeName="t02",targetState="stepFail",cond=whenReply("stepfail"))
				}	 
				state("stepDone") { //this:State
					action { //it:State
						updateResourceRep("stepDone")
						mapRoomKotlin.mapUtil.doMove( "w"  )
						mapRoomKotlin.mapUtil.showMap(  )
						delay(500) 
					}
					 transition(edgeName="t03",targetState="stopped",cond=whenDispatch("stop"))
					transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("stepFail") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						mapRoomKotlin.mapUtil.doMove( "h"  )
						
									NumStep++
									var Dt = 0L 			
						if( checkMsgContent( Term.createTerm("stepfail(DURATION,CAUSE)"), Term.createTerm("stepfail(DURATION,CAUSE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 Dt = payloadArg(0).toLong()   
								if(  Dt < 3*StepTime/4.0   
								 ){forward("cmd", "cmd(s)" ,"basicrobot" ) 
								delay(Dt)
								forward("cmd", "cmd(h)" ,"basicrobot" ) 
								}
								updateResourceRep("stepFail")
								delay(1000) 
						}
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						delay(500) 
						mapRoomKotlin.mapUtil.doMove( "l"  )
					}
					 transition(edgeName="t04",targetState="stopped",cond=whenDispatch("stop"))
					transition( edgeName="goto",targetState="work", cond=doswitchGuarded({ NumStep<4  
					}) )
					transition( edgeName="goto",targetState="endWork", cond=doswitchGuarded({! ( NumStep<4  
					) }) )
				}	 
				state("stopped") { //this:State
					action { //it:State
						println("robotboundary | stopped")
						updateResourceRep("stopped")
					}
					 transition(edgeName="t05",targetState="work",cond=whenDispatch("resume"))
				}	 
				state("endWork") { //this:State
					action { //it:State
						Workduration = getDuration(StartTime)
						println("robotboundary | ends; duration=$Workduration")
						updateResourceRep("terminated")
						terminate(0)
					}
				}	 
			}
		}
}
