/* Generated by AN DISI Unibo */ 
package it.unibo.waiter

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Waiter ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var CurrentClientId        	= 0
		   var CurrentSelectedTable   	= 0
		   var CurMoveX  			  	= 0
		   var CurMoveY  				= 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						itunibo.planner.plannerUtil.initAI(  )
						solve("consult('tearoomkb.pl')","") //set resVar	
					}
					 transition(edgeName="t00",targetState="someQuery",cond=whenEvent("walkerstarted"))
				}	 
				state("someQuery") { //this:State
					action { //it:State
						println("waiter | sending some query ... ")
						solve("teatable(1,ST)","") //set resVar	
						if( currentSolution.isSuccess() ) { val S = getCurSol("ST").toString()    
						println("waiter | teatable 1 state=$S")
						}
						else
						{}
						solve("numavailabletables(N)","") //set resVar	
						if( currentSolution.isSuccess() ) { val Ntables = getCurSol("N").toString().toInt()   
						println("waiter | numavailabletables=$Ntables")
						}
						else
						{}
						solve("roomstate(V)","") //set resVar	
						if( currentSolution.isSuccess() ) { val W = getCurSol("V").toString()   
						println("waiter | $W  ")
						}
						else
						{}
						println(" ------------- end of Queries ----------------  ")
					}
					 transition( edgeName="goto",targetState="listening", cond=doswitch() )
				}	 
				state("listening") { //this:State
					action { //it:State
						 
									CurrentClientId        	= 0
									CurrentSelectedTable   	= 0
									CurMoveX  			  	= 0
									CurMoveY  				= 0			
					}
					 transition(edgeName="t01",targetState="handleEnterrequest",cond=whenRequest("enterrequest"))
				}	 
				state("handleEnterrequest") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						if( checkMsgContent( Term.createTerm("enterrequest(ID)"), Term.createTerm("enterrequest(CID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 CurrentClientId = payloadArg(0).toString().toInt()  
								solve("tableavailable(N)","") //set resVar	
								if( currentSolution.isSuccess() ) { CurrentSelectedTable = getCurSol("N").toString().toInt()   
								println("waiter | tableavailable=$CurrentSelectedTable")
								answer("enterrequest", "enteranswer", "enteranswer($CurrentSelectedTable)"   )  
								solve("engageTable($CurrentSelectedTable,$CurrentClientId)","") //set resVar	
								}
								else
								{answer("enterrequest", "enteranswer", "enteranswer(0)"   )  
								}
						}
					}
					 transition( edgeName="goto",targetState="listening", cond=doswitchGuarded({ CurrentClientId == 0  
					}) )
					transition( edgeName="goto",targetState="gotoEntrance", cond=doswitchGuarded({! ( CurrentClientId == 0  
					) }) )
				}	 
				state("gotoEntrance") { //this:State
					action { //it:State
						solve("pos(entrancedoor,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) { CurMoveX = getCurSol("X").toString().toInt()  
						 			   CurMoveY = getCurSol("Y").toString().toInt()  
						request("movetoCell", "movetoCell($CurMoveX,$CurMoveY)" ,"waiterwalker" )  
						}
						else
						{}
					}
					 transition(edgeName="t02",targetState="deployCurrentclient",cond=whenReply("atcell"))
					transition(edgeName="t03",targetState="unexpected",cond=whenReply("walkbreak"))
				}	 
				state("deployCurrentclient") { //this:State
					action { //it:State
						solve("pos(teatable,$CurrentSelectedTable,X,Y)","") //set resVar	
						if( currentSolution.isSuccess() ) { CurMoveX = getCurSol("X").toString().toInt()  
						 			   CurMoveY = getCurSol("Y").toString().toInt() - 1  //cell near the se
						request("movetoCell", "movetoCell($CurMoveX,$CurMoveY)" ,"waiterwalker" )  
						}
						else
						{}
					}
					 transition(edgeName="t04",targetState="clientdeployed",cond=whenReply("atcell"))
					transition(edgeName="t05",targetState="unexpected",cond=whenReply("walkbreak"))
				}	 
				state("clientdeployed") { //this:State
					action { //it:State
						println("client $CurrentClientId deployed to ($CurMoveX, $CurMoveY)")
					}
					 transition( edgeName="goto",targetState="listening", cond=doswitch() )
				}	 
				state("endOfJob") { //this:State
					action { //it:State
						itunibo.planner.plannerUtil.showCurrentRobotState(  )
						println("END OF Job ... BYE")
					}
				}	 
				state("unexpected") { //this:State
					action { //it:State
						println("There is something wrong ...")
						println("$name in ${currentState.stateName} | $currentMsg")
					}
				}	 
			}
		}
}
